# Form implementation generated from reading ui file 'ui files\login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_loginWindow(object):
    def setupUi(self, loginWindow):
        loginWindow.setObjectName("loginWindow")
        loginWindow.resize(450, 266)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui files\\../icon/donga.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        loginWindow.setWindowIcon(icon)
        self.label_3 = QtWidgets.QLabel(parent=loginWindow)
        self.label_3.setGeometry(QtCore.QRect(70, 20, 321, 23))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.taiKhoan_lineEdit = QtWidgets.QLineEdit(parent=loginWindow)
        self.taiKhoan_lineEdit.setGeometry(QtCore.QRect(140, 80, 231, 20))
        self.taiKhoan_lineEdit.setObjectName("taiKhoan_lineEdit")
        self.label_2 = QtWidgets.QLabel(parent=loginWindow)
        self.label_2.setGeometry(QtCore.QRect(50, 121, 81, 16))
        self.label_2.setObjectName("label_2")
        self.matKhau_lineEdit = QtWidgets.QLineEdit(parent=loginWindow)
        self.matKhau_lineEdit.setGeometry(QtCore.QRect(140, 121, 231, 20))
        self.matKhau_lineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.matKhau_lineEdit.setObjectName("matKhau_lineEdit")
        self.label = QtWidgets.QLabel(parent=loginWindow)
        self.label.setGeometry(QtCore.QRect(50, 80, 81, 16))
        self.label.setObjectName("label")
        self.dong_pushButton = QtWidgets.QPushButton(parent=loginWindow)
        self.dong_pushButton.setGeometry(QtCore.QRect(240, 180, 107, 31))
        self.dong_pushButton.setObjectName("dong_pushButton")
        self.dangNhap_pushButton = QtWidgets.QPushButton(parent=loginWindow)
        self.dangNhap_pushButton.setGeometry(QtCore.QRect(100, 180, 108, 31))
        self.dangNhap_pushButton.setObjectName("dangNhap_pushButton")

        self.retranslateUi(loginWindow)
        QtCore.QMetaObject.connectSlotsByName(loginWindow)

    def retranslateUi(self, loginWindow):
        _translate = QtCore.QCoreApplication.translate
        loginWindow.setWindowTitle(_translate("loginWindow", "Đăng nhập"))
        self.label_3.setText(_translate("loginWindow", "ĐĂNG NHẬP VÀO HỆ THỐNG"))
        self.label_2.setText(_translate("loginWindow", "Mật khẩu"))
        self.label.setText(_translate("loginWindow", "Tên đăng nhập"))
        self.dong_pushButton.setText(_translate("loginWindow", "Đóng"))
        self.dangNhap_pushButton.setText(_translate("loginWindow", "Đăng nhập"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    loginWindow = QtWidgets.QWidget()
    ui = Ui_loginWindow()
    ui.setupUi(loginWindow)
    loginWindow.show()
    sys.exit(app.exec())
