# Form implementation generated from reading ui file 'ui files\main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(740, 477)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/nguye/OneDrive/Hình ảnh/donga.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        mainWindow.setWindowIcon(icon)
        mainWindow.setStyleSheet("")
        self.label_2 = QtWidgets.QLabel(parent=mainWindow)
        self.label_2.setGeometry(QtCore.QRect(250, 100, 461, 351))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:/Users/nguye/OneDrive/Hình ảnh/TOTO-100-scaled.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.groupBox = QtWidgets.QGroupBox(parent=mainWindow)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 741, 81))
        self.groupBox.setStyleSheet("background-color: rgba(0, 119, 182,1)\n"
"\n"
"")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(110, 20, 531, 41))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white")
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(parent=mainWindow)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 100, 181, 351))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.muonTra_pushButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.muonTra_pushButton.setObjectName("muonTra_pushButton")
        self.verticalLayout.addWidget(self.muonTra_pushButton)
        self.banDoc_pushButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.banDoc_pushButton.setObjectName("banDoc_pushButton")
        self.verticalLayout.addWidget(self.banDoc_pushButton)
        self.tacGia_pushButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.tacGia_pushButton.setObjectName("tacGia_pushButton")
        self.verticalLayout.addWidget(self.tacGia_pushButton)
        self.admin_pushButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.admin_pushButton.setObjectName("admin_pushButton")
        self.verticalLayout.addWidget(self.admin_pushButton)
        self.viPham_pushButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.viPham_pushButton.setObjectName("viPham_pushButton")
        self.verticalLayout.addWidget(self.viPham_pushButton)
        self.theLoai_pushButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.theLoai_pushButton.setObjectName("theLoai_pushButton")
        self.verticalLayout.addWidget(self.theLoai_pushButton)
        self.sach_pushButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.sach_pushButton.setObjectName("sach_pushButton")
        self.verticalLayout.addWidget(self.sach_pushButton)
        self.thongKe_pushButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.thongKe_pushButton.setObjectName("thongKe_pushButton")
        self.verticalLayout.addWidget(self.thongKe_pushButton)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Trang chủ"))
        self.label.setText(_translate("mainWindow", "QUẢN LÝ THƯ VIỆN TRƯỜNG ĐẠI HỌC"))
        self.muonTra_pushButton.setText(_translate("mainWindow", "Lịch sử mượn trả"))
        self.banDoc_pushButton.setText(_translate("mainWindow", "Quản lý bạn đọc"))
        self.tacGia_pushButton.setText(_translate("mainWindow", "Quản lý tác giả"))
        self.admin_pushButton.setText(_translate("mainWindow", "Quản lý Admin"))
        self.viPham_pushButton.setText(_translate("mainWindow", "Quản lý vi phạm"))
        self.theLoai_pushButton.setText(_translate("mainWindow", "Quản lý thể loại"))
        self.sach_pushButton.setText(_translate("mainWindow", "Quản lý sách"))
        self.thongKe_pushButton.setText(_translate("mainWindow", "Thống kê"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QWidget()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec())
